### ISSUE TITLE
build error: Unable to satisfy dependency

### ISSUE THREAD

**Issue by maggu2810** [revelc/formatter-maven-plugin#95]
I tried to build the current master without success.

```text
formatter-maven-plugin $ git clean -x -d -f

formatter-maven-plugin $ git rev-parse HEAD
814a97ce098f250e64e238910be48996c3a37492

formatter-maven-plugin $ mvn -U clean install
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option PermSize=512m; support was removed in 8.0
Java HotSpot(TM) 64-Bit Server VM warning: ignoring option MaxPermSize=1g; support was removed in 8.0
[INFO] Scanning for projects...
[INFO] Inspecting build with total of 10 modules...
[INFO] Installing Nexus Staging features:
[INFO]   ... total of 10 executions of maven-deploy-plugin replaced with nexus-staging-maven-plugin
Downloading: https://repo.maven.apache.org/maven2/com/mycila/license-maven-plugin/maven-metadata.xml
log4j:WARN No appenders could be found for logger (org.apache.maven.wagon.providers.http.httpclient.client.protocol.RequestAddCookies).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Downloaded: https://repo.maven.apache.org/maven2/com/mycila/license-maven-plugin/maven-metadata.xml (625 B at 1.7 KB/sec)
[INFO] Computing target platform for MavenProject: net.revelc.code.formatter:jdt-core:1.6.0-SNAPSHOT @ /home/rathgeb/workspace/projects-oss/formatter-maven-plugin/formatters/jdt-core/pom.xml
[INFO] Resolving dependencies of MavenProject: net.revelc.code.formatter:jdt-core:1.6.0-SNAPSHOT @ /home/rathgeb/workspace/projects-oss/formatter-maven-plugin/formatters/jdt-core/pom.xml
[INFO] Cannot complete the request.  Generating details.
[INFO] Cannot complete the request.  Generating details.
[INFO] {osgi.os=win32, osgi.ws=win32, org.eclipse.update.install.features=true, osgi.arch=x86}
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: jdt-core 1.6.0.qualifier
[ERROR]   Missing requirement: jdt-core 1.6.0.qualifier requires 'bundle org.eclipse.jdt.core [1.0.0,10.0.0)' but it could not be found
[ERROR] 
[ERROR] Internal error: java.lang.RuntimeException: No solution found because the problem is unsatisfiable.: [Unable to satisfy dependency from jdt-core 1.6.0.qualifier to bundle org.eclipse.jdt.core [1.0.0,10.0.0).; No solution found because the problem is unsatisfiable.] -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.RuntimeException: No solution found because the problem is unsatisfiable.: [Unable to satisfy dependency from jdt-core 1.6.0.qualifier to bundle org.eclipse.jdt.core [1.0.0,10.0.0).; No solution found because the problem is unsatisfiable.]
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:121)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.RuntimeException: No solution found because the problem is unsatisfiable.: [Unable to satisfy dependency from jdt-core 1.6.0.qualifier to bundle org.eclipse.jdt.core [1.0.0,10.0.0).; No solution found because the problem is unsatisfiable.]
	at org.eclipse.tycho.p2.util.resolution.AbstractResolutionStrategy.newResolutionException(AbstractResolutionStrategy.java:98)
	at org.eclipse.tycho.p2.util.resolution.ProjectorResolutionStrategy.resolve(ProjectorResolutionStrategy.java:88)
	at org.eclipse.tycho.p2.util.resolution.AbstractResolutionStrategy.resolve(AbstractResolutionStrategy.java:63)
	at org.eclipse.tycho.p2.resolver.P2ResolverImpl.resolveDependencies(P2ResolverImpl.java:166)
	at org.eclipse.tycho.p2.resolver.P2ResolverImpl.resolveDependencies(P2ResolverImpl.java:103)
	at org.eclipse.tycho.p2.resolver.P2DependencyResolver.doResolveDependencies(P2DependencyResolver.java:352)
	at org.eclipse.tycho.p2.resolver.P2DependencyResolver.resolveDependencies(P2DependencyResolver.java:325)
	at org.eclipse.tycho.core.resolver.DefaultTychoResolver.resolveProject(DefaultTychoResolver.java:107)
	at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.afterProjectsRead(TychoMavenLifecycleParticipant.java:75)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:266)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	... 11 more
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/InternalErrorException
```

**Comment by ctubbsii** [comment]
I could not reproduce with OpenJDK7 or OpenJDK8. (Though I did run into other problems building with 8 using Maven 3.0.5... the first of which was the enforcer requiring at least Maven 3.2.5, which i think is a bit too strict.)

**Comment by maggu2810** [comment]
Hm, tried it on another machine and it is working there.
So, sorry for the issue.
I will compare the Java and Maven versions on my machines.

**Comment by trumpetx** [comment]
I am also getting this error on the two machines where I need it to be built.  On my home machine, it runs fine.  I don't think this issue is a problem, per se; however, the error message should give indication on how to fix the build machine:

`<?xml version="1.0" encoding="UTF-8"?>
<configuration>
  <resolver>p2</resolver>
  <ignoreTychoRepositories>true</ignoreTychoRepositories>
  <pomDependencies>consider</pomDependencies>
  <environments>
    <environment>
      <os>win32</os>
      <ws>win32</ws>
      <arch>x86</arch>
    </environment>
    <environment>
      <os>linux</os>
      <ws>gtk</ws>
      <arch>x86_64</arch>
    </environment>
    <environment>
      <os>macosx</os>
      <ws>cocoa</ws>
      <arch>x86_64</arch>
    </environment>
  </environments>
</configuration>
Debug options:
    file:/Users/davidgreene/IdeaProjects/formatter-maven-plugin/.options not found
Time to load bundles: 241
!SESSION 2016-10-18 09:46:57.693 -----------------------------------------------
eclipse.buildId=unknown
java.version=1.8.0_40
java.vendor=Oracle Corporation
BootLoader constants: OS=macosx, ARCH=x86_64, WS=cocoa, NL=en_US
Framework arguments:  -eclipse.keyring /var/folders/21/f1n8zg0n4zq_1gn7rhb8vwlw0000gp/T/tycho5123973320578866599secure_storage
Command-line arguments:  -eclipse.keyring /var/folders/21/f1n8zg0n4zq_1gn7rhb8vwlw0000gp/T/tycho5123973320578866599secure_storage -debug -consoleLog

!ENTRY org.eclipse.core.net 1 0 2016-10-18 09:46:57.694
!MESSAGE System property http.nonProxyHosts has been set to local|*.local|169.254/16|*.169.254/16 by an external source. This value will be overwritten using the values from the preferences
[DEBUG] Clearing proxy settings in OSGi runtime
[DEBUG] Dependency collection stats: {ConflictMarker.analyzeTime=1, ConflictMarker.markTime=0, ConflictMarker.nodeCount=88, ConflictIdSorter.graphTime=0, ConflictIdSorter.topsortTime=0, ConflictIdSorter.conflictIdCount=42, ConflictIdSorter.conflictIdCycleCount=0, ConflictResolver.totalTime=2, ConflictResolver.conflictItemCount=87, DefaultDependencyCollector.collectTime=42, DefaultDependencyCollector.transformTime=3}
[DEBUG] org.eclipse.tycho:tycho-p2-plugin:jar:0.21.0:
[DEBUG]    org.apache.maven:maven-plugin-api:jar:3.0:compile
[DEBUG]       org.apache.maven:maven-model:jar:3.0:compile
[DEBUG]       org.apache.maven:maven-artifact:jar:3.0:compile
[DEBUG]       org.sonatype.sisu:sisu-inject-plexus:jar:1.4.2:compile
[DEBUG]          org.sonatype.sisu:sisu-inject-bean:jar:1.4.2:compile
[DEBUG]             org.sonatype.sisu:sisu-guice:jar:noaop:2.1.7:compile
[DEBUG]    org.apache.maven:maven-core:jar:3.0:compile
[DEBUG]       org.apache.maven:maven-settings:jar:3.0:compile
[DEBUG]       org.apache.maven:maven-settings-builder:jar:3.0:compile
[DEBUG]       org.apache.maven:maven-repository-metadata:jar:3.0:compile
[DEBUG]       org.apache.maven:maven-model-builder:jar:3.0:compile
[DEBUG]       org.apache.maven:maven-aether-provider:jar:3.0:runtime
[DEBUG]       org.sonatype.aether:aether-impl:jar:1.7:compile
[DEBUG]          org.sonatype.aether:aether-spi:jar:1.7:compile
[DEBUG]       org.sonatype.aether:aether-api:jar:1.7:compile
[DEBUG]       org.sonatype.aether:aether-util:jar:1.7:compile
[DEBUG]       org.codehaus.plexus:plexus-interpolation:jar:1.14:compile
[DEBUG]       org.codehaus.plexus:plexus-utils:jar:3.0.7:compile
[DEBUG]       org.codehaus.plexus:plexus-classworlds:jar:2.2.3:compile
[DEBUG]       org.codehaus.plexus:plexus-component-annotations:jar:1.5.5:compile
[DEBUG]       org.sonatype.plexus:plexus-sec-dispatcher:jar:1.3:compile
[DEBUG]          org.sonatype.plexus:plexus-cipher:jar:1.7:compile
[DEBUG]    org.eclipse.tycho:sisu-equinox-launching:jar:0.21.0:compile
[DEBUG]       org.eclipse.tycho:tycho-core:jar:0.21.0:compile
[DEBUG]          org.codehaus.plexus:plexus-archiver:jar:2.2:compile
[DEBUG]             org.codehaus.plexus:plexus-io:jar:2.0.5:compile
[DEBUG]          org.eclipse.tycho:org.eclipse.osgi.compatibility.state:jar:1.0.0.v20140403-1907:compile
[DEBUG]          org.eclipse.tycho:tycho-metadata-model:jar:0.21.0:compile
[DEBUG]             de.pdark:decentxml:jar:1.3:compile
[DEBUG]          org.eclipse.tycho:tycho-embedder-api:jar:0.21.0:compile
[DEBUG]             org.eclipse.tycho:org.eclipse.tycho.embedder.shared:jar:0.21.0:compile
[DEBUG]          org.eclipse.tycho:org.eclipse.tycho.core.shared:jar:0.21.0:compile
[DEBUG]       org.eclipse.tycho:sisu-equinox-api:jar:0.21.0:compile
[DEBUG]       org.apache.commons:commons-exec:jar:1.2:compile
[DEBUG]    org.eclipse.tycho:tycho-p2-facade:jar:0.21.0:compile
[DEBUG]       org.eclipse.tycho:sisu-equinox-embedder:jar:0.21.0:compile
[DEBUG]          org.eclipse.tycho:org.eclipse.osgi:jar:3.10.0.v20140606-1445:compile
[DEBUG]       org.eclipse.tycho:org.eclipse.tycho.p2.resolver.shared:jar:0.21.0:compile
[DEBUG]       org.eclipse.tycho:org.eclipse.tycho.p2.tools.shared:jar:0.21.0:compile
[DEBUG]    org.eclipse.tycho:tycho-artifactcomparator:jar:0.21.0:compile
[DEBUG]       org.ow2.asm:asm-debug-all:jar:4.0:compile
[DEBUG] Created new class realm plugin>org.eclipse.tycho:tycho-p2-plugin:0.21.0
[DEBUG] Importing foreign packages into class realm plugin>org.eclipse.tycho:tycho-p2-plugin:0.21.0
[DEBUG]   Imported:  < project>net.revelc.code.formatter:parent:1.6.0-SNAPSHOT
[DEBUG] Populating class realm plugin>org.eclipse.tycho:tycho-p2-plugin:0.21.0
[DEBUG]   Included: org.eclipse.tycho:tycho-p2-plugin:jar:0.21.0
[DEBUG]   Included: org.sonatype.sisu:sisu-inject-bean:jar:1.4.2
[DEBUG]   Included: org.sonatype.sisu:sisu-guice:jar:noaop:2.1.7
[DEBUG]   Included: org.sonatype.aether:aether-util:jar:1.7
[DEBUG]   Included: org.codehaus.plexus:plexus-interpolation:jar:1.14
[DEBUG]   Included: org.codehaus.plexus:plexus-utils:jar:3.0.7
[DEBUG]   Included: org.codehaus.plexus:plexus-component-annotations:jar:1.5.5
[DEBUG]   Included: org.sonatype.plexus:plexus-sec-dispatcher:jar:1.3
[DEBUG]   Included: org.sonatype.plexus:plexus-cipher:jar:1.7
[DEBUG]   Included: org.eclipse.tycho:sisu-equinox-launching:jar:0.21.0
[DEBUG]   Included: org.codehaus.plexus:plexus-archiver:jar:2.2
[DEBUG]   Included: org.codehaus.plexus:plexus-io:jar:2.0.5
[DEBUG]   Included: org.eclipse.tycho:org.eclipse.osgi.compatibility.state:jar:1.0.0.v20140403-1907
[DEBUG]   Included: org.apache.commons:commons-exec:jar:1.2
[DEBUG]   Included: org.eclipse.tycho:tycho-artifactcomparator:jar:0.21.0
[DEBUG]   Included: org.ow2.asm:asm-debug-all:jar:4.0
[INFO] Computing target platform for MavenProject: net.revelc.code.formatter:jdt-core:1.6.0-SNAPSHOT @ /Users/davidgreene/IdeaProjects/formatter-maven-plugin/formatters/jdt-core/pom.xml
[DEBUG] Using execution environment 'JavaSE-1.7' configured in Bundle-RequiredExecutionEnvironment
[DEBUG] Registered artifact repository org.eclipse.tycho.repository.registry.facade.RepositoryBlackboardKey(uri=file:/resolution-context-artifacts@/Users/davidgreene/IdeaProjects/formatter-maven-plugin/formatters/jdt-core)
[DEBUG] Added 0 locally built units to the target platform
[INFO] Resolving dependencies of MavenProject: net.revelc.code.formatter:jdt-core:1.6.0-SNAPSHOT @ /Users/davidgreene/IdeaProjects/formatter-maven-plugin/formatters/jdt-core/pom.xml
[INFO] Cannot complete the request.  Generating details.
[INFO] Cannot complete the request.  Generating details.
[INFO] {osgi.os=win32, osgi.ws=win32, org.eclipse.update.install.features=true, osgi.arch=x86}
[ERROR] Cannot resolve project dependencies:
[ERROR]   Software being installed: jdt-core 1.6.0.qualifier
[ERROR]   Missing requirement: jdt-core 1.6.0.qualifier requires 'bundle org.eclipse.jdt.core [1.0.0,10.0.0)' but it could not be found
[ERROR]
[ERROR] Internal error: java.lang.RuntimeException: No solution found because the problem is unsatisfiable.: [Unable to satisfy dependency from jdt-core 1.6.0.qualifier to bundle org.eclipse.jdt.core [1.0.0,10.0.0).; No solution found because the problem is unsatisfiable.] -> [Help 1]
org.apache.maven.InternalErrorException: Internal error: java.lang.RuntimeException: No solution found because the problem is unsatisfiable.: [Unable to satisfy dependency from jdt-core 1.6.0.qualifier to bundle org.eclipse.jdt.core [1.0.0,10.0.0).; No solution found because the problem is unsatisfiable.]
       	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:121)
       	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
       	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
       	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
       	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
       	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       	at java.lang.reflect.Method.invoke(Method.java:497)
       	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
       	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
       	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
       	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.RuntimeException: No solution found because the problem is unsatisfiable.: [Unable to satisfy dependency from jdt-core 1.6.0.qualifier to bundle org.eclipse.jdt.core [1.0.0,10.0.0).; No solution found because the problem is unsatisfiable.]
       	at org.eclipse.tycho.p2.util.resolution.AbstractResolutionStrategy.newResolutionException(AbstractResolutionStrategy.java:98)
       	at org.eclipse.tycho.p2.util.resolution.ProjectorResolutionStrategy.resolve(ProjectorResolutionStrategy.java:88)
       	at org.eclipse.tycho.p2.util.resolution.AbstractResolutionStrategy.resolve(AbstractResolutionStrategy.java:63)
       	at org.eclipse.tycho.p2.resolver.P2ResolverImpl.resolveDependencies(P2ResolverImpl.java:166)
       	at org.eclipse.tycho.p2.resolver.P2ResolverImpl.resolveDependencies(P2ResolverImpl.java:103)
       	at org.eclipse.tycho.p2.resolver.P2DependencyResolver.doResolveDependencies(P2DependencyResolver.java:352)
       	at org.eclipse.tycho.p2.resolver.P2DependencyResolver.resolveDependencies(P2DependencyResolver.java:325)
       	at org.eclipse.tycho.core.resolver.DefaultTychoResolver.resolveProject(DefaultTychoResolver.java:107)
       	at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.afterProjectsRead(TychoMavenLifecycleParticipant.java:75)
       	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:266)
       	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
       	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
       	... 11 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/InternalErrorException`
